name: LocalStack Test
on: push

jobs:
  localstack-action-test:
    name: 'Test LocalStack GitHub Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start LocalStack
        uses: localStack/setup-localstack@v0.1.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
          configuration: DEBUG=1

      - name: Run Tests against LocalStack
        run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
          echo "Test Execution complete!"
